services:
  general-gis:
    # platform: linux/amd64
    build:
      context: .
      dockerfile: Dockerfile_general-gis
    image: proj-soils_general-gis

    # have to be specified (<local_dir>:<container_dir>)
    volumes:
      - .:/proj-soils/
      - /mnt/proj-soils/data/:/proj-soils/data/

    ports:
      - 8888:8888 # jupyter
      - 5678:5678 # debugpy

    stdin_open: true  # docker run -i
    tty: true         # docker run -t

  inference-ofs:
    # platform: linux/amd64
    build:
      context: .
      dockerfile: Dockerfile_inference-ofs
    image: proj-soils_inference-ofs

    # have to be specified (<local_dir>:<container_dir>)
    volumes:
      - .:/proj-soils/
      - /mnt/proj-soils/data/:/proj-soils/data/

    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    ports:
      - 5678:5678 # debugpy
      - 6006:6006 # tensorboard
    #   - 8888:8888 # jupyter
    stdin_open: true  # docker run -i
    tty: true         # docker run -t
  
  model-heigvd:
    build:
      context: .
      dockerfile: Dockerfile_model-heigvd
    image: proj-soils_model-heigvd
    shm_size: '4gb'
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]