rescale_tif.py:
  tiff_folder: /Users/nicibe/Desktop/Job/swisstopo_stdl/soil_fribourg/data/datasets/dataset_shanci_multiclass/1-5ch
  out_folder: /Users/nicibe/Desktop/Job/swisstopo_stdl/soil_fribourg/data/datasets/dataset_shanci_multiclass/2-40cm
  target_res: 0.4
  log_file: /Users/nicibe/Desktop/Job/swisstopo_stdl/soil_fribourg/proj-soils/logs/rescale.log


cut_tiff_to_grid.py:
  tiff_folder: /Users/nicibe/Desktop/Job/swisstopo_stdl/soil_fribourg/data/datasets/dataset_shanci_multiclass/2-40cm
  out_folder: /Users/nicibe/Desktop/Job/swisstopo_stdl/soil_fribourg/data/datasets/dataset_shanci_multiclass/3-scratch_tiles_512px_40cm
  grid_path: /Users/nicibe/Desktop/Job/swisstopo_stdl/soil_fribourg/data/heig-vd_finetuned/recursive_grids_max204-8m.gpkg
  grid_query: "depth == 2"
  cell_length: 512
  mask_path: 
  id_column: str_ids
  log_file: /Users/nicibe/Desktop/Job/swisstopo_stdl/soil_fribourg/proj-soils/logs/cut_tiff_to_grid.log


random_split.py:
  source_ipt_folder: /Users/nicibe/Desktop/Job/swisstopo_stdl/soil_fribourg/data/datasets/dataset_shanci_multiclass/3-scratch_tiles_512px_40cm
  source_tgt_folder: /Users/nicibe/Desktop/Job/swisstopo_stdl/soil_fribourg/data/GT/20240216/4-cut-to-grid-12cl/40cm/512px
  target_root: /Users/nicibe/Desktop/Job/swisstopo_stdl/soil_fribourg/data/datasets/dataset_shanci_multiclass/4-dataset_seed6-adj
  seed: 
  split_file: /Users/nicibe/Desktop/Job/swisstopo_stdl/soil_fribourg/data/datasets/dataset_shanci_multiclass/4-dataset_seed6-adj copy/split.yaml
  log_file: /Users/nicibe/Desktop/Job/swisstopo_stdl/soil_fribourg/proj-soils/logs/random_split.log