version: "3"
services:
  general-gis:
    # platform: linux/amd64
    build:
      context: .
      dockerfile: Dockerfile_general-gis
    image: proj-soils_general-gis

    # have to be specified (<local_dir>:<container_dir>)
    volumes:
      - .:/proj-soils/
      - /mnt/s3/proj-soils/data/:/proj-soils/data/

    ports:
      - 8888:8888 # jupyter
      # - 5678:5678 # debugpy

    stdin_open: true  # docker run -i
    tty: true         # docker run -t

  model-heigvd:
    # platform: linux/amd64
    build:
      context: .
      dockerfile: Dockerfile_model-heigvd
    image: proj-soils_model-heigvd
    shm_size: '4gb'
    
    # have to be specified (<local_dir>:<container_dir>)
    volumes:
      - .:/proj-soils
      - /mnt/s3/proj-soils/data/:/proj-soils/data/
      # encoder_decoder_mask2former.py
      - type: bind
        source: ./scripts/heigvd/model/encoder_decoder_mask2former.py
        target: /ViT-Adapter/segmentation/mmseg_custom/models/segmentors/encoder_decoder_mask2former.py
      # proj_soils.py
      - type: bind
        source: ./scripts/heigvd/code/proj_soils.py
        target: /ViT-Adapter/segmentation/mmseg_custom/datasets/proj_soils.py
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    ports:
      - 5678:5678
      # - 8888:8888
      
    stdin_open: true  # docker run -i
    tty: true         # docker run -t