rgbi2rgb.py:
  source_folder: /proj-soil/data/scratch/0-AOIs/
  target_folder: /proj-soil/data/scratch/1-rgb
  log_file: /proj-soil/logs/rgbi2rgb.log

rescale_tif.py:
  tiff_folder: /proj-soil/data/scratch/1-rgb
  out_folder: /proj-soil/data/scratch/2-10cm
  target_res: 0.1
  log_file: /proj-soil/logs/rescale.log

cut_tiff_to_grid.py:
  tiff_folder: /proj-soil/data/scratch/2-10cm
  out_folder: /proj-soil/data/scratch/3-cut-to-grid/10cm/512px
  grid_path: /proj-soil/data/grids/recursive_grids_max204-8m_51-2m.gpkg
  grid_query: "depth == 0"
  cell_length: 512
  mask_path: 
  id_column: str_ids
  log_file: /proj-soil/logs/cut_tiff_to_grid.log