rescale_tif.py:
  tiff_folder: /proj-soil/data/GT/20240216/3-rasterized-12cl/10cm
  out_folder: /proj-soil/data/GT/20240216/3-rasterized-12cl/40cm
  target_res: 0.4
  log_file: /proj-soil/proj-soil/logs/rescale.log

cut_tiff_to_grid.py:
  tiff_folder: /proj-soil/data/GT/20240216/3-rasterized-12cl/40cm
  out_folder: /proj-soil/data/GT/20240216/4-cut-to-grid-12cl/40cm/512px
  grid_path: /proj-soil/data/heig-vd_finetuned/recursive_grids_max204-8m.gpkg
  grid_query: "depth == 2"
  cell_length: 512
  mask_path: 
  id_column: str_ids
  log_file: /proj-soil/proj-soil/logs/cut_tiff_to_grid.log

random_split.py:
  source_ipt_folder: /proj-soil/data/scratch/horizontal_scratch_mosaics-rgb/3-cut_to_grid/40cm/512px
  source_tgt_folder: /proj-soil/data/GT/20240216/4-cut-to-grid-12cl/40cm/512px
  target_root: /proj-soil/data/datasets.nosync/dataset_12cl_seed6-adjusted_multiscale
  seed: 
  split_file: /proj-soil/data/datasets.nosync/seed6_adjusted_split.yaml
  log_file: /proj-soil/proj-soil/logs/random_split.log