rescale_tif.py:
  tiff_folder: /Users/nicibe/Desktop/Job/swisstopo_stdl/soil_fribourg/data/GT/20240216/4-cut-to-grid-12cl/10cm/2048px
  target_res:  0.2
  out_folder:  /Users/nicibe/Desktop/Job/swisstopo_stdl/soil_fribourg/data/GT/20240216/4-cut-to-grid-12cl/20cm/1024px
  log_file: /Users/nicibe/Desktop/Job/swisstopo_stdl/soil_fribourg/proj-soils/logs/rescale_tif.log

calculate_metrics.py:
  pred_folder: /Users/nicibe/Desktop/Job/swisstopo_stdl/soil_fribourg/data/heig-vd_finetuned/0-inferences/10cm_71k/20cm
  gt_folder: /Users/nicibe/Desktop/Job/swisstopo_stdl/soil_fribourg/data/GT/20240216/4-cut-to-grid-12cl/20cm/1024px-val
  metric_csv_path_multiclass: /Users/nicibe/Desktop/Job/swisstopo_stdl/soil_fribourg/proj-soils/csv/metrics/metrics_heigvd-10cm-71k-20cm_mc_seed6-adjusted.csv
  metric_csv_path_binary:     /Users/nicibe/Desktop/Job/swisstopo_stdl/soil_fribourg/proj-soils/csv/metrics/metrics_heigvd-10cm-71k-20cm_bn_seed6-adjusted.csv
  count_csv_path_multiclass: /Users/nicibe/Desktop/Job/swisstopo_stdl/soil_fribourg/proj-soils/csv/counts/counts_heigvd-10cm-71k-20cm_mc_seed6-adjusted.csv
  count_csv_path_binary:     /Users/nicibe/Desktop/Job/swisstopo_stdl/soil_fribourg/proj-soils/csv/counts/counts_heigvd-10cm-71k-20cm_bn_seed6-adjusted.csv
  conf_matrix_path_multiclass: /Users/nicibe/Desktop/Job/swisstopo_stdl/soil_fribourg/proj-soils/figures/conf_matrices/cm_heigvd-10cm-71k-20cm_mc_seed6-adjusted.png
  conf_matrix_path_binary:     /Users/nicibe/Desktop/Job/swisstopo_stdl/soil_fribourg/proj-soils/figures/conf_matrices/cm_heigvd-10cm-71k-20cm_bn_seed6-adjusted.png
  conf_matrix_model: heigvd-10cm-71k_20cm
  classes: ["batiment", "surface_non_beton",
    "surface_beton", "roche_dure_meuble", "eau_naturelle",
    "roseliere", "sol_neige", "sol_vegetalise",
    "sol_divers", "sol_vigne", "sol_agricole", "sol_bache"]
  soil_classes: [7, 8, 9, 10, 11, 12]
  create_cm: True
  same_names: True
  exclude_ids: []
  log_file: /Users/nicibe/Desktop/Job/swisstopo_stdl/soil_fribourg/proj-soils/logs/calculate_metrics.log