infere_heigvd.py:
  config: /proj-soil/scripts/heigvd/model/mask2former_beit_adapter_large_512_160k_proj-soils_12class_10cm.py
  checkpoint: ../../proj-soil/data/model_weights/heig-vd_finetuned/10cm_best_mIoU_iter_71280.pth
  source_folder: [../../proj-soil/data/scratch/3-cut-to-grid/10cm/512px/]
  target_folder: [../../proj-soil/data/inference/heigvd/seed6-adjusted/10cm_71k/10cm]
  stride: [512]
  side_length: [[2048, 2048]]
  device: "cuda:0"
  palette: None
  log_file: ../../proj-soil/logs/infere_heigvd.log

