infere_heigvd.py:
  config: /proj-soil/scripts/heigvd/model/mask2former_beit_adapter_large_512_160k_proj-soils_12class_multiscale.py
  checkpoint: /proj-soil/data/inference_heigvd/mixed_best_mIoU_iter_145320.pth
  source_folder: [/proj-soil/data/scratch_val-seed6-adj_large/40cm]
  target_folder: [/proj-soil/data/inference_heigvd/seed6-adjusted/mixed_145k/40cm]
  stride: [512]
  side_length: [[512, 512]]
  device: "cuda:0"
  palette: None
  log_file: /proj-soil/logs/infere_heigvd.log

