rescale_tif.py:
  tiff_folder: [
    /proj-soil/data/scratch_test_rgb_1km/10cm,
    /proj-soil/data/scratch_test_rgb_1km/10cm,
    /proj-soil/data/scratch_test_rgb_1km/10cm
    ]
  target_res: [0.1, 0.2, 0.4]
  out_folder: [
    /proj-soil/data/scratch_test_rgb_1km/10cm,
    /proj-soil/data/scratch_test_rgb_1km/20cm,
    /proj-soil/data/scratch_test_rgb_1km/40cm
  ]
  log_file: /proj-soil/logs/rescale_tif.log

infere_heigvd.py:
  config: /proj-soil/scripts/heigvd/model/mask2former_beit_adapter_large_512_160k_proj-soils_12class_10cm.py
  checkpoint: /proj-soil/data/inference_heigvd/10cm_best_mIoU_iter_71280.pth
  source_folder: [
    /proj-soil/data/scratch_test_rgb_1km/10cm,
    /proj-soil/data/scratch_test_rgb_1km/20cm,
    /proj-soil/data/scratch_test_rgb_1km/40cm,
    ]
  target_folder: [
    /proj-soil/data/inference_heigvd/testscratch/10cm-71k/stride512/10cm,
    /proj-soil/data/inference_heigvd/testscratch/10cm-71k/stride512/20cm,
    /proj-soil/data/inference_heigvd/testscratch/10cm-71k/stride512/40cm,
    ]
  stride: [512, 512, 512]
  side_length: [[10000, 10000], [5000, 5000], [2500, 2500]]
  device: "cuda:0"
  palette: None
  log_file: /proj-soil/logs/infere_heigvd.log 
