#######################################################################
## Configuration file to prepare the IGN predictions for evaluation  ##
#######################################################################


reclassify.py:
  source_folder: /proj-soil/data/IGN/0-0-all_tifs
  target_folder: /proj-soil/data/IGN/1-reclassified
  mapping: {
    1: 1, 2: 2, 3: 3, 4: 4, 5: 5, 6: 6, 7: 7, 8: 8, 9: 8, 10: 8, 11: 8,
    12: 8, 13: 8, 15: 8, 14: 9, 16: 10, 17: 10, 18: 11
  }
  log_file: /proj-soil/logs/reclassify.log


cut_tiff_to_grid.py:
  tiff_folder: /proj-soil/data/IGN/1-reclassified
  out_folder: /proj-soil/data/IGN/2-cut_to_grid/1024px_extent1
  grid_path: /proj-soil/data/grid_102-4m_only-gt37.gpkg
  cell_length: 1024
  mask_path: /proj-soil/data/GT/20231004/0-cleaned
  id_column: id
  log_file: /proj-soil/logs/cut_tiff_to_grid.log

mask_tiffs.py:
  source_folder: /proj-soil/data/IGN/2-cut_to_grid/1024px_extent1/odeon-unet-vgg16_RVBI
  target_folder: /proj-soil/data/IGN/2-cut_to_grid/1024px_extent1-masked/odeon-unet-vgg16_RVBI
  mask: /proj-soil/data/GT/GT_extent1_batiments.gpkg
  nodata: 255
  log_file: /proj-soil/logs/mask_tiffs.log


######################
##### multiclass #####
######################

# extent 1
calculate_metrics.py:
  pred_folder: /proj-soil/data/IGN/2-cut_to_grid/1024px_extent1
  gt_folder: /proj-soil/data/GT/20231004/3-cut_to_grid/1024px_extent1
  metric_csv_path: /proj-soil/csv/metrics/metrics_IGN_multiclass_extent1.csv
  count_csv_path: /proj-soil/csv/counts/counts_IGN_multiclass_extent1.csv
  conf_matrix_model: smp-unet-resnet34-imagenet_RVBI
  classes: [ batiment, surface_non_beton, surface_beton, eau_bassin,
            roche_dure_meuble, eau_naturelle, sol_neige, sol_vegetalise,
            sol_vigne, sol_agricole, serre_permanente]
  create_cm: False
  exclude_ids: []
  log_file: /proj-soil/logs/calculate_metrics.log

# # extent 2
# calculate_metrics.py:
#   pred_folder: /proj-soil/data/IGN/2-cut_to_grid/1024px_extent1
#   gt_folder: /proj-soil/data/GT/20231004/3-cut_to_grid/1024px_extent1
#   metric_csv_path: /proj-soil/csv/metrics/metrics_IGN_multiclass_extent2.csv
#   count_csv_path: /proj-soil/csv/counts/counts_IGN_multiclass_extent2.csv
#   conf_matrix_model: smp-unet-resnet34-imagenet_RVBI
#   classes: [ batiment, surface_non_beton, surface_beton, eau_bassin,
#             roche_dure_meuble, eau_naturelle, sol_neige, sol_vegetalise,
#             sol_vigne, sol_agricole, serre_permanente]
#   create_cm: False
#   exclude_ids: [1, 3, 9, 10, 14, 16, 17, 18, 22, 26, 30, 34, 35]
#   log_file: /proj-soil/logs/calculate_metrics.log

# # extent1-masked
# calculate_metrics.py:
#   pred_folder: /proj-soil/data/IGN/2-cut_to_grid/1024px_extent
#   gt_folder: /proj-soil/data/GT/20231004/3-cut_to_grid/1024px_extent1
#   metric_csv_path: /proj-soil/csv/metrics/metrics_IGN_multiclass_extent1-masked.csv
#   count_csv_path: /proj-soil/csv/counts/counts_IGN_multiclass_extent1-masked.csv
#   conf_matrix_model: smp-unet-resnet34-imagenet_RVBI
#   classes: [ batiment, surface_non_beton, surface_beton, eau_bassin,
#             roche_dure_meuble, eau_naturelle, sol_neige, sol_vegetalise,
#             sol_vigne, sol_agricole, serre_permanente]
#   create_cm: False
#   exclude_ids: []
#   log_file: /proj-soil/logs/calculate_metrics.log


######################
####### binary #######
######################

# extent1
calculate_metrics_soil-nonsoil.py:
  pred_folder: /proj-soil/data/IGN/2-cut_to_grid/1024px_extent1
  gt_folder: /proj-soil/data/GT/20231004/3-cut_to_grid/1024px_extent1
  metric_csv_path: /proj-soil/csv/metrics/metrics_IGN_binary_extent1.csv
  count_csv_path: /proj-soil/csv/counts/counts_IGN_binary_extent1.csv
  conf_matrix_model: smp-unet-resnet34-imagenet_RVBI
  soil_classes: [7, 8, 9, 10]
  create_cm: False
  exclude_ids: []
  log_file: /proj-soil/logs/calculate_metrics_soil-nonsoil.log


# # extent 2
# calculate_metrics_soil-nonsoil.py:
#   pred_folder: /proj-soil/data/IGN/2-cut_to_grid/1024px_extent1
#   gt_folder: /proj-soil/data/GT/20231004/3-cut_to_grid/1024px_extent1
#   metric_csv_path: /proj-soil/csv/metrics/metrics_IGN_binary_extent2.csv
#   count_csv_path: /proj-soil/csv/counts/counts_IGN_binary_extent2.csv
#   conf_matrix_model: smp-unet-resnet34-imagenet_RVBI
#   soil_classes: [7, 8, 9, 10]
#   create_cm: False
#   exclude_ids: [1, 3, 9, 10, 14, 16, 17, 18, 22, 26, 30, 34, 35]
#   log_file: /proj-soil/logs/calculate_metrics_soil-nonsoil.log

# # extent1-masked
# calculate_metrics_soil-nonsoil.py:
#   pred_folder: /proj-soil/data/IGN/2-cut_to_grid/1024px_extent1-masked
#   gt_folder: /proj-soil/data/GT/20231004/3-cut_to_grid/1024px_extent1
#   metric_csv_path: /proj-soil/csv/metrics/metrics_ign_binary_extent1-masked.csv
#   count_csv_path: /proj-soil/csv/counts/counts_ign_binary_extent1-masked.csv
#   conf_matrix_model: smp-unet-resnet34-imagenet_RVBI
#   soil_classes: [7, 8, 9, 10]
#   create_cm: False
#   exclude_ids: []
#   log_file: /proj-soil/logs/calculate_metrics_soil-nonsoil.log