#######################################################################
## Configuration file to prepare the OFS predictions for evaluation  ##
#######################################################################

rescale_tif.py:
  tiff_folder: /proj-soil/data/OFS/2nd/1-reclassified
  out_folder:  /proj-soil/data/OFS/2nd/2-rescaled
  target_res: 0.1
  log_file: /proj-soil/rescale_tif.log

reclassify.py:
  source_folder: /proj-soil/data/OFS/2nd/0-raw
  target_folder: /proj-soil/data/OFS/2nd/1-reclassified
  mapping: {0: 0,
    11: 3, 12: 1, 13: 11, 14: 8, 15: 8, 16: 8, 17: 8, 21: 8, 31: 8,
    32: 8, 33: 8, 34: 9, 35: 8, 41: 8, 42: 8, 43: 8, 44: 8, 45: 8,
    46: 8, 47: 8, 51: 5, 52: 5, 53: 5, 61: 6, 62: 7, 63: 8, 64: 6,
  }
  log_file: /proj-soil/reclassify.log


cut_tiff_to_grid.py:
  tiff_folder: /proj-soil/data/OFS/2nd/2-rescaled
  out_folder: /proj-soil/data/OFS/2nd/3-cut_to_grid/val-seed6-adj/ADELE2SAM
  grid_path: /proj-soil/data/heig-vd_finetuned/recursive_grids_max204-8m.gpkg
  grid_query: "split == 'val' & depth == 0"
  cell_length: 512
  mask_path: 
  id_column: str_ids
  log_file: /proj-soil/cut_tiff_to_grid.log

calculate_metrics.py:
  pred_folder: /proj-soil/data/OFS/2nd/3-cut_to_grid/val-seed6-adj
  gt_folder: /proj-soil/data/GT/20240216/4-cut-to-grid-12cl/10cm/512px
  metric_csv_path_multiclass: /proj-soil/csv/metrics/metrics_ADELE2SAM-10cm_mc_seed6-adjusted.csv
  metric_csv_path_binary:     /proj-soil/csv/metrics/metrics_ADELE2SAM-10cm_bn_seed6-adjusted.csv
  count_csv_path_multiclass: /proj-soil/csv/counts/counts_ADELE2SAM-10cm_mc_seed6-adjusted.csv
  count_csv_path_binary:     /proj-soil/csv/counts/counts_ADELE2SAM-10cm_bn_seed6-adjusted.csv
  conf_matrix_path_multiclass: /proj-soil/figures/conf_matrices/cm_ADELE2SAM-10cm_mc_seed6-adjusted.png
  conf_matrix_path_binary:     /proj-soil/figures/conf_matrices/cm_ADELE2SAM-10cm_bn_seed6-adjusted.png
  conf_matrix_model: ADELE2SAM
  classes: ["batiment", "surface_non_beton",
    "surface_beton", "roche_dure_meuble", "eau_naturelle",
    "roseliere", "sol_neige", "sol_vegetalise",
    "sol_divers", "sol_vigne", "sol_agricole", "sol_bache"]
  soil_classes: [7, 8, 9, 10, 11, 12]
  create_cm: True
  same_names: True
  exclude_ids: []
  log_file: /proj-soil/logs/calculate_metrics.log
