calculate_metrics.py:
  pred_folder: /proj-soil/data/heig-vd_finetuned/0-inferences/seed6-adjusted/mixed_145k/10cm
  gt_folder: /proj-soil/data/GT/20240216/4-cut-to-grid-12cl/10cm/2048px-val
  metric_csv_path_multiclass: /proj-soil/csv/metrics/metrics_heigvd-mixed-145k-10cm_mc_seed6-adjusted.csv
  metric_csv_path_binary:     /proj-soil/csv/metrics/metrics_heigvd-mixed-145k-10cm_bn_seed6-adjusted.csv
  count_csv_path_multiclass: /proj-soil/csv/counts/counts_heigvd-mixed-145k-10cm_mc_seed6-adjusted.csv
  count_csv_path_binary:     /proj-soil/csv/counts/counts_heigvd-mixed-145k-10cm_bn_seed6-adjusted.csv
  conf_matrix_path_multiclass: /proj-soil/figures/conf_matrices/cm_heigvd-mixed-145k-10cm_mc_seed6-adjusted.png
  conf_matrix_path_binary:     /proj-soil/figures/conf_matrices/cm_heigvd-mixed-145k-10cm_bn_seed6-adjusted.png
  conf_matrix_model: heigvd-mixed-145k_10cm
  classes: ["batiment", "surface_non_beton",
    "surface_beton", "roche_dure_meuble", "eau_naturelle",
    "roseliere", "sol_neige", "sol_vegetalise",
    "sol_divers", "sol_vigne", "sol_agricole", "sol_bache"]
  soil_classes: [7, 8, 9, 10, 11, 12]
  create_cm: True
  same_names: True
  exclude_ids: []
  log_file: /proj-soil/logs/calculate_metrics.log